export const items = [
  {
    sys: { id: 0 },
    fields: {
      title: "OIGNONS",
      description: "Besla",
      categorie: "fruits_legumes",
      price: 10,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/oignons.jpg" } } },
    },
  },
  {
    sys: { id: 1 },
    fields: {
      title: "VALENCIA",
      description: "BOISSON COCKTAIL VALENCIA JUPER",
      categorie: "boissons",
      price: 12,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/valencia.jpg" } } },
    },
  },
  {
    sys: { id: 2 },
    fields: {
      title: "COCA-COLA 1,5L",
      description: "Coca-Cola classique",
      categorie: "boissons",
      price: 10,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/coca.png" } } },
    },
  },
  {
    sys: { id: 3 },
    fields: {
      title: "PAMPERS",
      description: "Couches n° 1 et 2 - Mini 3-6 kg",
      categorie: "bebe",
      price: 111.0,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/pampers.jpg" } } },
    },
  },
  {
    sys: { id: 4 },
    fields: {
      title: "ARIEL",
      description: "ariel",
      categorie: "entretien",
      price: 128.95,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/ariel.jpg" } } },
    },
  },
  {
    sys: { id: 5 },
    fields: {
      title: "KOUTOUBIA - DÉCOUPE",
      description: "Pilons de poulet",
      categorie: "poissons_viandes",
      price: 55.0,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/koutoubia1.png" } } },
    },
  },

  {
    sys: { id: 6 },
    fields: {
      title: "BOULANGERIE",
      description: "Hamburger",
      categorie: "cuisine",
      price: 7,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/painhumberger.png" } } },
    },
  },
  {
    sys: { id: 7 },
    fields: {
      title: "NESTLÉ",
      description: "Cerelac - Fruits",
      categorie: "Bebe",
      price: 28.95,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/nestlé.jpg" } } },
    },
  },
  {
    sys: { id: 8 },
    fields: {
      title: "PÊCHE",
      description: "Lkhoukh",
      categorie: "fruits_legumes",
      price: 15.0,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/peche.jpg" } } },
    },
  },
  {
    sys: { id: 9 },
    fields: {
      title: "BOULANGERIE",
      description: "Pain sandwich",
      categorie: "cuisine",
      price: 3.5,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/painsandwich.jpg" } } },
    },
  },
  {
    sys: { id: 10 },
    fields: {
      title: "RENOVA",
      description: "Essuie-tout",
      categorie: "entretien",
      price: 18.5,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/renova.jpg" } } },
    },
  },
  {
    sys: { id: 11 },
    fields: {
      title: "KOUTOUBIA - DÉCOUPE",
      description: "Escalopes de dinde",
      categorie: "poissons_viandes",
      price: 53.0,
      quantity: 10,
      featured: true,
      image: { fields: { file: { url: "img/koutoubia2.jpg" } } },
    },
  },
  {
    sys: { id: 12 },
    fields: {
      title: "CHOU-FLEUR",
      description: "Shôfla",
      categorie: "fruits_legumes",
      price: 8.0,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/choufleur.jpg" } } },
    },
  },
  {
    sys: { id: 13 },
    fields: {
      title: "TOMATES",
      description: "Maticha",
      categorie: "fruits_legumes",
      price: 5.0,
      quantity: 10,
      featured: false,
      image: { fields: { file: { url: "img/tomate.jpg" } } },
    },
  },
];
